name: "Robot Configuration File"
frontLeftDriveName: "front_left_drive"
frontRightDriveName: "front_right_drive"
backLeftDriveName: "back_left_drive"
backRightDriveName: "back_right_drive"
imuName: "imu"
servoName: "servo"
limelightName: "limelight"
intakeMotorName: "intake_motor"
flywheelMotor1Name: "flywheel_1"
flywheelMotor2Name: "flywheel_2"
